# Generated by Django 3.2.8 on 2021-11-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NITE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(choices=[("'7378106'", "'7378106'"), (" '2548755'", " '2548755'"), (" '8954763'", " '8954763'")])),
            ],
        ),
    ]
